language: go
os:
  - linux
  - osx
go:
- '1.11'
env:
- GO111MODULE=on
script: make
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y upx; fi
  - make dist-release
deploy:
  provider: releases
  api_key:
    secure: h3mk8yLr3X9Fi6N5izV12kd78WipRqyMeHgp+pI7vXISvVlvX5xLRZ5gvPJlA45/rLb6zvxFdWw3g11wjpxiL0uvCFpXESWUWLp6/iBZM1AoCCT2gK/IWUenQGwFRj9an6FVgpj2Rx9kCveNjw0mfzNyftP8UO/LzBxZsM1tOjYJpR5F0v7JlXXWHejOCbFjuxFQDqTfFEhEjsuzLHbERZW7RmRWeda//vK1VMkaWvSi0ihCWTKxi/nkD2K+1Bh8u7AETfTcAs7x7YpW0e3QJfi7kemgVOTn9/fklQsYfMp2rb2P1YZTU3cqvaXK1V9axZXk1yV2gKGNYnwcKzR1imG7lJylZCeUvTLBYYHeqxdETkRe4nvMMwRc1M1u3ErDJKNlw1VeH6Qf3AAwERDnEjATgQeIyE/Oya/A+mRBqCkJAD/ImN4vXLJ4YxiKEQsLXTj35hxBR0Ep3UvGXG/xKimEVRwIwfBXcPqoJwmCGk2m+SMfhOBuUnujZFsEsjeCSv5Q4o/xabtRp0EO5/OKiPRtjNHurfU13ha2xsSTkzs6jTAjUVH8+eJezb/kSy1+gjWsltLthnnZTCL8TF/zW6Dfte5LqhB5AUXt5GjhWBUg9S1aLRSCn1bvt7aE5c2bfMbBp0OXZpY9KrpiOcqZGri08ejaPfj1THcCBNjAYvs=
  file_glob: true
  file: build/*.tar.gz*
  skip_cleanup: true
  on:
    repo: lyraproj/lyra
    tags: true