apiVersion: lyra.example.com/v1alpha1
kind: Workflow
metadata:
  name: sample2-workflow
spec:
  workflowName: "sample2"
  data:
    foo: kubeFooooo
    bar: kubeBaaaar
    baz: kubeBaaaaz
  refreshTime: 10
